site_name: ELIXIR Training Lesson
nav:
    - About: index.md
    - Course Content:
      - "1. What is version control": chapters/chapter_01.md
      - "2. Git & Git hosting services": chapters/chapter_02.md
      - "3. Getting familiar with Git and GitHub": chapters/chapter_03.md
      - "4. Learn the workflow from case studies": chapters/chapter_04.md
      - "5. Advanced topics": chapters/chapter_05.md
      - "6. Data management, data sharing & ethical issues": chapters/chapter_06.md
      - "References": chapters/references.md
    - "Follow up training": follow_up_training.md

theme:
  name: material
  logo: assets/images/white-orange-logo.png
  favicon: assets/images/elixir_favicon.ico
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.footer
    - toc.integrate
  font: 
    text: Lato

# Repository
repo_name: elixir-europe-training/ELIXIR-TrP-VersionControlPython-CodeRep
repo_url: https://github.com/elixir-europe-training/ELIXIR-TrP-VersionControlPython-CodeRep
edit_uri: edit/main/docs/

plugins:
  - tags:
      tags_file: keywords.md
  - search
  - bibtex:
      bib_file: "references.bib"
  - mkdocs-video # embed videos to the docs

  
# Footer
copyright: By the ELIXIR Training Platform

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc:
      toc_depth: 3
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - neoteroi.cards



extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css

